[tool.poetry]
name = "logger"
version = "1.1.3"
description = "common logger, which can auto print log"
authors = ["XDeviation <191602098@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
